export { default as Footer }                from './Footer'
export { default as Layout }                from './Layout'
export { default as Loader }                from './Loader'
export { default as NumberedHeading }       from './NumberedHeading'
export { default as SocialsList }           from './SocialsList'